version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y python3-pip
      - /usr/bin/python3 -m pip install openai
      
      # Retrieve the API key from AWS Secrets Manager
      - |
        api_key=$(aws secretsmanager get-secret-value --secret-id OPENAI_API_KEY --region eu-north-1 --query SecretString --output text)
        if [ -z "$api_key" ]; then
          echo "Failed to retrieve API key from Secrets Manager"
          exit 1
        fi
        
        # Set the API key as an environment variable
        export OPENAI_API_KEY="$api_key"

  build:
    commands:
      - /usr/bin/python3 my_openai.py

artifacts:
  files: '**/*'











