version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Adjust to your required Python version
    commands:
      - pip install openai

  build:
    commands:
      - python run_openai_script.py

artifacts:
  files: '**/*'


