version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update
      - apt-get install -y python3-pip
      - /usr/bin/python3 -m pip install --upgrade pip
      - /usr/bin/python3 -m pip install openai

  build:
    commands:
      - export OPENAI_API_KEY=$OPENAI_API_KEY
      - /usr/bin/python3 run_openai_script.py

artifacts:
  files: '**/*'






