version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y python3-pip
      - /usr/bin/python3 -m pip install openai

  build:
    commands:
      - /usr/bin/python3 my_openai.py

artifacts:
  files: '**/*'











