version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install system dependencies
      - yum install -y python3 python3-pip

      # Install virtualenv
      - /usr/bin/python3 -m pip install virtualenv

      # Create a virtual environment
      - virtualenv env

      # Activate the virtual environment
      - source env/bin/activate

      # Upgrade the openai package
      - pip install --upgrade openai

      # Retrieve the API key from GitHub secrets
      - |
        export OPENAI_API_KEY=$(echo "${{ secrets.OPENAI_API_KEY }}")

  build:
    commands:
      # Make a request using the OpenAI Python client
      - python my_openai.py

artifacts:
  files: '**/*'














